/* =================================================================
   DATOS: BANCO DE 150 PREGUNTAS  [modulo, pregunta, [opciones], correctaIdx, explicacion]
================================================================= */
const QB = [
[1,"¿En qué año se inventó el baloncesto?",["1881","1891","1901","1871"],1,"El baloncesto fue creado en diciembre de 1891 por James Naismith."],
[1,"¿En qué institución fue creado el baloncesto?",["Harvard University","Springfield College","Yale University","MIT"],1,"Naismith lo creó en Springfield College, Massachusetts."],
[1,"¿Quién fue el creador del baloncesto?",["James Naismith","John Wooden","Luther Gulick","Dean Smith"],0,"El Dr. James Naismith, profesor de Educación Física, creó el baloncesto."],
[1,"¿Cuál era la nacionalidad del Dr. James Naismith?",["Estadounidense","Canadiense","Inglés","Escocés"],1,"Naismith era un profesor canadiense de Educación Física."],
[1,"¿Cuál fue el propósito original al crear el baloncesto?",["Sustituir el fútbol americano en verano","Crear una alternativa de bajo impacto en ambiente cerrado durante el invierno","Entrenar boxeadores","Reemplazar el atletismo"],1,"Buscaba un deporte de bajo impacto para practicarse en interiores durante el invierno."],
[1,"¿Qué deporte inspiró la mecánica de los pases del baloncesto?",["Rugby estadounidense","Béisbol","Voleibol","Hockey"],0,"El rugby estadounidense inspiró la mecánica de los pases."],
[1,"¿Qué deporte inspiró los saltos en el baloncesto?",["Rugby inglés","Atletismo","Fútbol","Boxeo"],0,"El rugby inglés inspiró los saltos del juego."],
[1,"¿Qué juego infantil inspiró la puntería a un objetivo elevado?",["Pato en la roca","Herradura","Tiro al blanco","Bolos"],0,"\"Pato en una roca\" inspiró la puntería hacia un objetivo elevado."],
[1,"¿Cuál fue la propuesta inicial de nombre para el nuevo deporte?",["Juego Naismith","Basket Game","Cesta Ball","Netball"],0,"Se propuso inicialmente el nombre \"Juego Naismith\"."],
[1,"¿Qué nombre prevaleció finalmente para el deporte?",["Basket Game","Baloncesto","Cesta Ball","Netball"],1,"Finalmente prevaleció el nombre de Baloncesto."],
[1,"¿Dónde se disputó el primer partido internacional de baloncesto en 1893?",["Montmartre, París","Londres","Berlín","Nueva York"],0,"El primer partido internacional se jugó en Montmartre, París, en 1893."],
[1,"¿Qué liga fundada en 1898 es considerada la primera liga profesional de baloncesto?",["NBA","NBL","BAA","ABA"],1,"La NBL, fundada en 1898, fue la primera liga profesional."],
[1,"¿En qué país se fundó la FIBA en 1932?",["Francia","Suiza","Estados Unidos","Bélgica"],1,"La FIBA se fundó en Suiza en 1932."],
[1,"¿En qué edición de los Juegos Olímpicos debutó el baloncesto masculino?",["Los Ángeles 1932","Berlín 1936","Londres 1948","París 1924"],1,"El baloncesto masculino debutó en los Juegos Olímpicos de Berlín 1936."],
[1,"¿En qué edición de los Juegos Olímpicos debutó el baloncesto femenino?",["Múnich 1972","Montreal 1976","Moscú 1980","Los Ángeles 1984"],1,"El baloncesto femenino debutó en los Juegos Olímpicos de Montreal 1976."],
[2,"¿Cuáles son las medidas oficiales de la cancha según la FIBA?",["28 m x 15 m","26 m x 14 m","30 m x 16 m","24 m x 13 m"],0,"La cancha oficial FIBA mide 28 m de largo por 15 m de ancho."],
[2,"¿Cuál es el diámetro del círculo central?",["3.0 m","3.6 m","4.2 m","2.4 m"],1,"El círculo central tiene un diámetro de 3.6 m."],
[2,"¿Cuál es el radio del semicírculo de no carga bajo la canasta?",["1.00 m","1.25 m","1.50 m","1.75 m"],1,"El semicírculo de no carga tiene un radio de 1.25 m."],
[2,"¿Cuáles son las dimensiones oficiales del tablero?",["1.05 x 1.80 m","1.20 x 2.00 m","0.90 x 1.50 m","1.00 x 1.60 m"],0,"El tablero mide 1.05 x 1.80 m."],
[2,"¿Cuál es el grosor mínimo permitido del tablero?",["20 mm","30 mm","40 mm","50 mm"],1,"El grosor mínimo del tablero es de 30 mm."],
[2,"¿Cómo debe estar fijado el tablero?",["Suspendido libremente","Anclado al suelo","Sujeto solo al techo","Sobre ruedas"],1,"El tablero debe estar anclado firmemente al suelo."],
[2,"¿A qué altura debe estar el aro según el reglamento?",["2.90 m","3.05 m","3.20 m","3.50 m"],1,"El aro se coloca a 3.05 m de altura reglamentaria."],
[2,"¿A qué distancia se ubica el aro respecto a la línea de fondo?",["0.90 m","1.20 m","1.50 m","1.80 m"],1,"El aro se ubica a 1.20 m dentro del campo desde la línea de fondo."],
[2,"¿Cuántos puntos de agarre (grip points) tiene un balón oficial?",["7,200","9,366","10,500","8,000"],1,"El balón oficial tiene 9,366 puntos de agarre."],
[2,"En la prueba de rebote reglamentario, el balón se deja caer desde 1.80 m; ¿entre qué alturas debe rebotar?",["0.80-1.00 m","1.20-1.40 m","1.50-1.70 m","1.00-1.20 m"],1,"Debe rebotar entre 1.20 m y 1.40 m para considerarse reglamentario."],
[2,"¿Cuál es la circunferencia del balón categoría #7 (varonil)?",["69-70 cm","72-73 cm","74-76 cm","77-79 cm"],2,"El balón categoría #7 (varonil) mide entre 74 y 76 cm de circunferencia."],
[2,"¿Cuál es el rango de peso del balón categoría #7?",["470-510 g","510-567 g","567-610 g","620-650 g"],2,"El balón categoría #7 pesa entre 567 y 610 g."],
[2,"¿Cuál es la circunferencia del balón categoría #6 (femenil)?",["69-70 cm","72-73 cm","74-76 cm","76-78 cm"],1,"El balón categoría #6 (femenil) mide entre 72 y 73 cm."],
[2,"¿Cuáles son las medidas del balón categoría #5 (infantil)?",["69-70 cm, 470-510 g","72-73 cm, 510-567 g","74-76 cm, 567-610 g","65-67 cm, 400-450 g"],0,"El balón categoría #5 (infantil) mide 69-70 cm y pesa 470-510 g."],
[2,"¿Qué organismo internacional rige las especificaciones oficiales de la cancha y el equipamiento?",["NBA","FIBA","COI","ADEMEBA"],1,"La FIBA rige las especificaciones oficiales del equipamiento y la cancha."],
[3,"¿Qué indica un árbitro al señalar con los dedos hacia abajo (1 o 2 dedos)?",["Puntos anotados en tiro de campo","Falta técnica","Tiempo fuera","Sustitución"],0,"Los dedos hacia abajo indican los puntos anotados en tiro de campo."],
[3,"¿Qué significa la señal de 3 dedos levantados por el árbitro?",["Triple convertido","Intento de tiro de 3 puntos","Falta antideportiva","Tres faltas del equipo"],1,"Tres dedos levantados indican un intento de tiro de 3 puntos."],
[3,"¿Qué señal indica un triple convertido?",["3 dedos levantados","Palma abierta","Dos manos arriba","Puño cerrado"],2,"Dos manos arriba indican que el triple fue convertido."],
[3,"¿Qué señal usa el árbitro para detener el reloj de juego?",["Palma abierta","Puño cerrado","Corte con la mano","Dos manos arriba"],0,"La palma abierta indica detener el reloj."],
[3,"¿Qué indica el puño cerrado del árbitro?",["Reanudar el reloj","Falta cometida","Canasta anotada","Balón fuera"],1,"El puño cerrado indica una falta cometida."],
[3,"¿Qué señal se usa para reanudar el reloj de juego?",["Palma abierta","Puño cerrado","Corte con la mano","3 dedos"],2,"El corte con la mano indica reanudar el reloj."],
[3,"¿Qué gesto representa una falta técnica?",["Una \"T\" con las manos","Manos en la cintura","Puño cerrado","Palma abierta"],0,"La \"T\" formada con las manos representa una falta técnica."],
[3,"¿Qué señal indica un bloqueo?",["Manos en la cintura","Sujetar la muñeca sobre la cabeza","Una \"T\" con las manos","Puño cerrado"],0,"Las manos en la cintura señalan un bloqueo."],
[3,"¿Qué señal indica una falta antideportiva?",["Manos en la cintura","Sujetar la muñeca sobre la cabeza","Palma abierta","3 dedos"],1,"Sujetar la muñeca sobre la cabeza indica falta antideportiva."],
[3,"¿Con qué gesto se representa un bloqueo defensivo ilegal?",["Manos en la cintura","Puño cerrado","Corte con la mano","Palma abierta"],0,"El bloqueo se representa con las manos en la cintura."],
[3,"¿Qué figura arbitral, junto al árbitro principal, apoya el control del partido?",["El anotador","Los árbitros auxiliares","El entrenador","El capitán"],1,"Los árbitros auxiliares apoyan al árbitro principal en el control del partido."],
[3,"¿Cuál señal corporal indica claramente \"falta antideportiva\"?",["Sujetar la muñeca sobre la cabeza","3 dedos levantados","Palma abierta","Manos en la cintura"],0,"Sujetar la muñeca sobre la cabeza es la señal de falta antideportiva."],
[3,"¿Cuál señal se asocia a un intento fallido de triple?",["3 dedos levantados","Dos manos arriba","Puño cerrado","Palma abierta"],0,"3 dedos levantados indican intento de triple, convertido o no."],
[3,"¿Qué indica la señal de dos manos levantadas hacia arriba?",["Falta técnica","Triple convertido","Tiempo fuera","Balón fuera"],1,"Dos manos levantadas indican un triple convertido."],
[3,"¿Cuál es la función general de la señalización arbitral en el baloncesto?",["Comunicar decisiones de juego a jugadores y público","Reemplazar al anotador","Sustituir el reglamento","Decidir el marcador final"],0,"La señalización comunica de forma clara las decisiones arbitrales."],
[4,"¿Cuáles son los elementos de la postura defensiva obligatoria?",["Rodillas flexionadas, cadera baja, espalda recta, palmas arriba","Piernas rectas, espalda curva, manos abajo","Rodillas bloqueadas, cadera alta","Pies juntos, brazos cruzados"],0,"La postura defensiva exige rodillas flexionadas, cadera baja, espalda recta y palmas arriba."],
[4,"¿Cuáles son los tres elementos de la Trilogía Técnica?",["Bote, pase, tiro","Ataque, defensa, transición","Fuerza, velocidad, resistencia","Táctica, técnica, estrategia"],0,"La Trilogía Técnica está compuesta por el bote, el pase y el tiro."],
[4,"¿En qué situación se utiliza el bote de Protección?",["Bajo presión defensiva","En avance libre","Para crear espacio","En el rebote"],0,"El bote de Protección se usa bajo presión defensiva."],
[4,"¿Qué tipo de bote se usa para el avance sin oposición?",["Protección","Control","Alejamiento","Ninguno"],1,"El bote de Control se usa para avanzar sin oposición."],
[4,"¿Qué tipo de bote busca crear espacio o evitar un 2x1?",["Protección","Control","Alejamiento","Reversa"],2,"El bote de Alejamiento busca crear espacio o evitar un 2x1."],
[4,"¿Cuántos tipos de pase se describen en el compendio?",["5","6","8","10"],2,"Se describen 8 tipos de pase."],
[4,"¿Qué tipo de pase rebota en el piso antes de llegar al receptor?",["Pase de pecho","Pase picado","Pase elevado","Pase ciego"],1,"El pase picado rebota en el piso antes de llegar al receptor."],
[4,"¿Qué tipo de pase se realiza sin mirar directamente al receptor?",["Pase ciego","Pase al toque","Pase de béisbol","Pase saltando"],0,"El pase ciego se entrega sin mirar directamente al receptor."],
[4,"¿Qué tipo de pase se ejecuta con una sola mano a larga distancia, similar al lanzamiento de béisbol?",["Pase de pecho","Pase de béisbol","Pase picado","Pase al toque"],1,"El pase de béisbol se ejecuta a una mano y larga distancia."],
[4,"¿Cuántos tipos de tiro se mencionan en el compendio?",["4","5","7","9"],2,"Se mencionan 7 tipos de tiro."],
[4,"¿Cuál es el primer paso de la ciencia del rebote?",["Salto vertical","Brazos elevados","Toma en el punto más alto","Aseguramiento con ambas manos"],1,"El primer paso es elevar los brazos."],
[4,"¿Cuál es el segundo paso de la ciencia del rebote?",["Brazos elevados","Salto vertical","Protección al bajar","Aseguramiento con ambas manos"],1,"El segundo paso es el salto vertical."],
[4,"¿Cuál es el tercer paso de la ciencia del rebote?",["Toma en el punto más alto","Salto vertical","Brazos elevados","Protección al bajar"],0,"El tercer paso es la toma del balón en el punto más alto."],
[4,"¿Cuál es el cuarto paso de la ciencia del rebote?",["Brazos elevados","Aseguramiento con ambas manos","Salto vertical","Toma en el punto más alto"],1,"El cuarto paso es asegurar el balón con ambas manos."],
[4,"¿Cuál es el quinto y último paso de la ciencia del rebote?",["Salto vertical","Toma en el punto más alto","Protección al bajar (codos fuera)","Brazos elevados"],2,"El quinto paso es proteger el balón al bajar, con los codos hacia afuera."],
[5,"Según Matveiev (1986), ¿qué es el sentido táctico?",["La aptitud de identificar situaciones, prever acciones y elegir soluciones","La capacidad física máxima del jugador","El plan de entrenamiento anual","La ejecución perfecta de la técnica"],0,"Matveiev define el sentido táctico como la aptitud de identificar situaciones, prever acciones y elegir soluciones."],
[5,"¿Cuántos tipos de interacciones tácticas describen Bauer y Ueberle (1988)?",["3","4","5","6"],2,"Bauer y Ueberle describen 5 tipos de interacciones tácticas."],
[5,"¿Cuál NO es un tipo de interacción táctica según Bauer y Ueberle?",["Táctica individual","Táctica colectiva","Situaciones estándar","Táctica ofensiva-defensiva mixta"],3,"Los 5 tipos son: individual, colectiva, de equipo, situaciones estándar y práctica del día del partido."],
[5,"¿Cómo se define la Técnica dentro de la Tríada Deportiva?",["Ejecución de movimientos estructurales basados en patrones espaciales modelo","Plan a largo plazo para vencer al rival","Solución inmediata ante un oponente","Selección de deportistas"],0,"La técnica es la ejecución de movimientos basados en patrones espaciales modelo."],
[5,"¿Cuál es un ejemplo de Técnica según el compendio?",["Selección de deportistas","Mecánica de tiro y drible","Sistemas de juego","Plan de entrenamiento"],1,"La mecánica de tiro y el drible son ejemplos de técnica."],
[5,"¿Cómo se define la Táctica dentro de la Tríada Deportiva?",["Plan de acción a largo plazo","Proceso que conjuga facultades físicas, técnicas y psicológicas para solución inmediata","Ejecución de un patrón espacial fijo","Selección del personal técnico"],1,"La táctica conjuga facultades físicas, técnicas y psicológicas para una solución inmediata."],
[5,"¿Cuál es un ejemplo de Táctica según el compendio?",["Tiro con oposición y amagar pivote","Plan de entrenamiento anual","Selección de deportistas","Mecánica de tiro"],0,"El tiro con oposición y amagar pivote son ejemplos de táctica."],
[5,"¿Cómo se define la Estrategia dentro de la Tríada Deportiva?",["Ejecución técnica inmediata","Plan de acción definido a largo plazo para superar al oponente","Reacción instantánea ante el rival","Patrón espacial de movimiento"],1,"La estrategia es un plan de acción a largo plazo para superar al oponente."],
[5,"¿Cuál es un ejemplo de Estrategia según el compendio?",["Amagar pivote","Selección de deportistas y sistemas de juego","Mecánica de tiro","Tiro con oposición"],1,"La selección de deportistas y los sistemas de juego son ejemplos de estrategia."],
[5,"En el modelo táctico Overload, ¿cuántos jugadores se concentran en un mismo sector?",["2","3","4","5"],1,"En el Overload se concentran 3 jugadores en un mismo sector."],
[5,"¿Cuál es la zona de impacto del modelo Overload?",["Centro de la zona","Lateral y esquina","Línea de tiros libres","Medio campo"],1,"La zona de impacto del Overload es el lateral y la esquina."],
[5,"En el modelo High-Low, ¿quién distribuye el balón desde la bombilla?",["El base","El interior/pívot","El escolta","El entrenador"],1,"El interior distribuye el balón desde la bombilla en el High-Low."],
[5,"¿Cuál es la zona de impacto del modelo High-Low?",["Perímetro de 3 puntos","Centro de la zona y tiros libres","Esquina","Medio campo"],1,"La zona de impacto del High-Low es el centro de la zona y los tiros libres."],
[5,"¿Qué caracteriza al modelo Ball Reversal?",["Bote excesivo por un solo jugador","Circulación rápida del balón sin bote excesivo","Juego exclusivamente interior","Defensa individual"],1,"El Ball Reversal se caracteriza por la circulación rápida sin bote excesivo."],
[5,"En la defensa del poste bajo \"a tres cuartos\", ¿qué se busca principalmente?",["Defender con balón de frente","Evitar el pase cortando la línea con pie y mano","Permitir el pase para robar después","Doblar sobre el poste alto"],1,"La defensa a tres cuartos busca evitar el pase cortando la línea con pie y mano."],
[6,"¿Cuál es la primera etapa del ciclo de planificación del entrenamiento?",["Definición de objetivos","Análisis del estado del atleta","Selección de ejercicios","Evaluación de resultados"],1,"La primera etapa es el análisis del estado del atleta."],
[6,"¿Cuál es la segunda etapa del ciclo de planificación?",["Análisis del estado del atleta","Definición de objetivos","Estructuración de sesiones","Planificación de descansos"],1,"La segunda etapa es la definición de objetivos."],
[6,"¿Cuál es la tercera etapa del ciclo de planificación?",["Selección de ejercicios","Evaluación de resultados","Definición de objetivos","Planificación de descansos"],0,"La tercera etapa es la selección de ejercicios."],
[6,"¿Cuál es la cuarta etapa del ciclo de planificación?",["Estructuración de sesiones","Análisis del estado del atleta","Evaluación de resultados","Selección de ejercicios"],0,"La cuarta etapa es la estructuración de sesiones."],
[6,"¿Cuál es la quinta etapa del ciclo de planificación?",["Definición de objetivos","Planificación de descansos","Selección de ejercicios","Análisis del estado del atleta"],1,"La quinta etapa es la planificación de descansos."],
[6,"¿Cuál es la sexta y última etapa del ciclo de planificación?",["Evaluación de resultados","Estructuración de sesiones","Definición de objetivos","Análisis del estado del atleta"],0,"La sexta etapa es la evaluación de resultados."],
[6,"¿Cuántas etapas conforman el ciclo de planificación del entrenamiento?",["4","5","6","7"],2,"El ciclo se compone de 6 etapas."],
[6,"¿Qué etapa antecede directamente a \"selección de ejercicios\"?",["Análisis del estado del atleta","Definición de objetivos","Estructuración de sesiones","Evaluación de resultados"],1,"La definición de objetivos antecede a la selección de ejercicios."],
[6,"¿Qué etapa sigue inmediatamente después de \"estructuración de sesiones\"?",["Planificación de descansos","Evaluación de resultados","Definición de objetivos","Selección de ejercicios"],0,"Después de estructurar las sesiones sigue la planificación de descansos."],
[6,"¿Cuál es el propósito de la etapa de \"evaluación de resultados\"?",["Diseñar los ejercicios iniciales","Verificar el cumplimiento de objetivos y ajustar el plan","Sustituir a los entrenadores","Definir las reglas del juego"],1,"Esta etapa permite verificar el cumplimiento de objetivos y ajustar el plan."],
[6,"¿Por qué es relevante planificar los descansos dentro del ciclo de entrenamiento?",["Favorece la recuperación y previene el sobreentrenamiento","No influye en el rendimiento","Sustituye la evaluación de resultados","Elimina la necesidad de objetivos"],0,"Planificar los descansos favorece la recuperación y evita el sobreentrenamiento."],
[6,"¿Qué etapa implica conocer el nivel físico y técnico inicial del deportista?",["Análisis del estado del atleta","Estructuración de sesiones","Evaluación de resultados","Planificación de descansos"],0,"El análisis del estado del atleta permite conocer su nivel inicial."],
[6,"¿Qué etapa traduce los objetivos en actividades concretas de entrenamiento?",["Selección de ejercicios","Evaluación de resultados","Análisis del estado del atleta","Planificación de descansos"],0,"La selección de ejercicios traduce los objetivos en actividades concretas."],
[6,"El ciclo de planificación del entrenamiento se caracteriza por ser...",["Un proceso lineal y secuencial de etapas","Un evento único sin seguimiento","Una decisión exclusiva del árbitro","Una etapa aislada sin relación con el rendimiento"],0,"Es un proceso lineal y secuencial compuesto por 6 etapas."],
[6,"¿Qué etapa cierra el ciclo permitiendo iniciar un nuevo ciclo de mejora?",["Evaluación de resultados","Definición de objetivos","Selección de ejercicios","Análisis del estado del atleta"],0,"La evaluación de resultados cierra el ciclo y da paso a uno nuevo."],
[7,"¿En qué rango de edad se ubica la fase de Iniciación en la detección de talento?",["6-9 años","10-13 años","14-17 años","18-21 años"],0,"La fase de Iniciación abarca de 6 a 9 años."],
[7,"¿A qué categorías corresponde la fase de Iniciación?",["Micro e Infantil","Pasarela y Cadete","Juvenil y Juvenil Mayor","Sub-21"],0,"La fase de Iniciación corresponde a las categorías Micro e Infantil."],
[7,"¿Qué caracteriza a la fase de Iniciación?",["Alto rendimiento competitivo","100% lúdico, agilidad y coordinación ojo-mano","Evaluaciones estructuradas de estatura","Especialización posicional"],1,"La fase de Iniciación es 100% lúdica, centrada en agilidad y coordinación ojo-mano."],
[7,"¿En qué rango de edad se ubica la fase de Detección Activa?",["6-9 años","10-13 años","14-17 años","22-25 años"],1,"La fase de Detección Activa abarca de 10 a 13 años."],
[7,"¿A qué categorías corresponde la fase de Detección Activa?",["Micro e Infantil","Pasarela y Cadete","Juvenil y Juvenil Mayor","Máster"],1,"Corresponde a las categorías Pasarela y Cadete."],
[7,"¿Qué caracteriza a la fase de Detección Activa?",["Juego 100% libre","Evaluaciones estructuradas y predicción de estatura","Retiro deportivo","Selección profesional inmediata"],1,"Se caracteriza por evaluaciones estructuradas y predicción de estatura."],
[7,"¿En qué rango de edad se ubica la fase de Especialización?",["6-9 años","10-13 años","14-17 años","25-30 años"],2,"La fase de Especialización abarca de 14 a 17 años."],
[7,"¿A qué categorías corresponde la fase de Especialización?",["Micro e Infantil","Pasarela y Cadete","Juvenil y Juvenil Mayor","Veteranos"],2,"Corresponde a las categorías Juvenil y Juvenil Mayor."],
[7,"¿Qué caracteriza a la fase de Especialización?",["Juego exclusivamente recreativo","Alto rendimiento y adaptación post-estirón puberal","Ausencia de evaluación física","Enfoque únicamente táctico"],1,"Se caracteriza por el alto rendimiento y la adaptación post-estirón puberal."],
[7,"¿Qué es el Bio-Banding?",["Agrupar por edad cronológica estrictamente","Agrupar por maduración física real en lugar de edad cronológica","Un sistema de arbitraje","Un tipo de entrenamiento de fuerza"],1,"El Bio-Banding agrupa por maduración física real, no por edad cronológica."],
[7,"¿Qué problema busca evitar el Bio-Banding?",["Excluir a los \"maduradores tardíos\"","Aumentar el número de árbitros","Reducir el número de categorías","Eliminar las evaluaciones físicas"],0,"Busca evitar la exclusión de los \"maduradores tardíos\"."],
[7,"¿Cuántas fases sensibles de detección de talento se describen en el compendio?",["2","3","4","5"],1,"Se describen 3 fases sensibles."],
[7,"¿Cuál es la primera fase sensible de detección de talento?",["Especialización","Detección Activa","Iniciación","Bio-Banding"],2,"La primera fase sensible es la Iniciación."],
[7,"¿Cuál es la fase intermedia de detección de talento?",["Iniciación","Detección Activa","Especialización","Retiro"],1,"La fase intermedia es la Detección Activa."],
[7,"¿Cuál es la última fase, orientada al alto rendimiento?",["Iniciación","Detección Activa","Especialización","Bio-Banding"],2,"La última fase, orientada al alto rendimiento, es la Especialización."],
[8,"¿Qué afirmó el Dr. Burkhart sobre la relación visión-decisión-acción?",["El cuerpo actúa antes de que los ojos miren","Los ojos deben mirar y el cerebro decidir antes de que el cuerpo ejecute la acción","La decisión ocurre después de la acción","La visión no influye en la ejecución técnica"],1,"Burkhart afirma que los ojos miran y el cerebro decide antes de que el cuerpo actúe."],
[8,"¿Para qué sirve el entrenamiento visual cercano y lejano?",["Aumentar la fuerza muscular","Procesar detalles en milisegundos y mejorar la toma de decisiones","Reducir la estatura del jugador","Sustituir el entrenamiento técnico"],1,"Sirve para procesar detalles en milisegundos y mejorar la toma de decisiones."],
[8,"¿Con qué se relaciona principalmente la dimensión cognitiva en el baloncesto?",["La toma de decisiones","La resistencia aeróbica","La flexibilidad articular","El peso corporal"],0,"La dimensión cognitiva se relaciona principalmente con la toma de decisiones."],
[8,"Según Burkhart, ¿qué debe ocurrir antes de la ejecución motriz?",["La ejecución técnica automática","La decisión cerebral basada en lo que ven los ojos","El descanso muscular","La señal del árbitro"],1,"Debe ocurrir la decisión cerebral basada en lo que ven los ojos."],
[8,"¿Qué tipo de entrenamiento mejora la velocidad de procesamiento visual del jugador?",["Entrenamiento de fuerza máxima","Entrenamiento visual cercano y lejano","Entrenamiento de flexibilidad","Entrenamiento aeróbico continuo"],1,"El entrenamiento visual cercano y lejano mejora la velocidad de procesamiento."],
[8,"La capacidad de tomar decisiones rápidas en milisegundos se asocia principalmente a...",["La dimensión física","La dimensión cognitiva","La dimensión histórica","La dimensión reglamentaria"],1,"Se asocia principalmente a la dimensión cognitiva."],
[8,"Además de la dimensión física, ¿qué otra dimensión es esencial en el rendimiento del jugador?",["La dimensión cognitiva","La dimensión estética","La dimensión administrativa","La dimensión climática"],0,"La dimensión cognitiva es esencial junto con la física."],
[8,"El entrenamiento cognitivo-visual busca reducir principalmente...",["El tiempo de reacción y decisión","El tamaño de la cancha","El número de árbitros","La duración del partido"],0,"Busca reducir el tiempo de reacción y decisión del jugador."],
[8,"¿Qué relación existe entre percepción visual y ejecución técnica según el compendio?",["No existe relación entre ambas","La percepción visual antecede y guía la ejecución técnica","La ejecución técnica antecede a la percepción","Son procesos completamente independientes"],1,"La percepción visual antecede y guía la ejecución técnica."],
[8,"¿Por qué es relevante procesar información en milisegundos en el baloncesto?",["El juego exige decisiones rápidas ante estímulos cambiantes","No influye en el rendimiento competitivo","Solo aplica a los árbitros","Es relevante únicamente en el entrenamiento de fuerza"],0,"El juego exige decisiones rápidas ante estímulos que cambian constantemente."],
[8,"La cita del Dr. Burkhart resalta principalmente la importancia de...",["La secuencia visión-decisión-acción","La fuerza explosiva de piernas","El tamaño del balón","La duración de los cuartos"],0,"Resalta la secuencia visión-decisión-acción."],
[8,"¿Qué dimensión estudia cómo el jugador percibe y decide durante el juego?",["Dimensión histórica","Dimensión cognitiva","Dimensión arbitral","Dimensión organizacional"],1,"La dimensión cognitiva estudia la percepción y la decisión del jugador."],
[8,"El trabajo de visión periférica se relaciona principalmente con...",["La postura defensiva y la anticipación","El peso del balón","La altura del aro","El tipo de cancha"],0,"La visión periférica se relaciona con la postura defensiva y la anticipación."],
[8,"¿Qué componente del rendimiento integra lo físico y lo cognitivo en el jugador?",["La capacidad de decisión táctica","El tamaño del uniforme","La antigüedad del club","El color del balón"],0,"La capacidad de decisión táctica integra lo físico y lo cognitivo."],
[8,"En el contexto del compendio, ¿qué papel cumple el cerebro según Burkhart?",["Tomar la decisión antes de que el cuerpo ejecute la acción","Ejecutar la acción motriz directamente","Sustituir la función de los ojos","No tiene un papel relevante en el juego"],0,"El cerebro toma la decisión antes de que el cuerpo ejecute la acción."],
[9,"¿Qué tipos de fracturas se mencionan como lesiones técnicas del baloncesto?",["Agudas o por estrés","Solo agudas","Solo por estrés","Congénitas"],0,"Se mencionan fracturas agudas o por estrés."],
[9,"¿Qué implica un esguince Grado I?",["Ruptura total del ligamento","Distensión ligamentosa sin ruptura","Ruptura parcial del ligamento","Fractura ósea"],1,"El esguince Grado I implica una distensión ligamentosa sin ruptura."],
[9,"¿Qué implica un esguince Grado II?",["Distensión leve","Ruptura parcial del ligamento","Ruptura total del ligamento","Tendinitis crónica"],1,"El esguince Grado II implica una ruptura parcial del ligamento."],
[9,"¿Qué implica un esguince Grado III?",["Distensión leve","Ruptura parcial","Ruptura total del ligamento","Ninguna lesión"],2,"El esguince Grado III implica la ruptura total del ligamento."],
[9,"¿Qué ejemplo de tendinitis se menciona en el compendio?",["Tendinitis rotuliana","Tendinitis de Aquiles","Tendinitis del manguito rotador","Tendinitis de muñeca"],1,"Se menciona la tendinitis de Aquiles como ejemplo."],
[9,"¿Cuál es un síntoma característico de una lesión aguda?",["Dolor intenso y repentino","Dolor leve y constante en reposo","Ausencia total de dolor","Dolor solo después de una semana"],0,"El dolor intenso y repentino es característico de la lesión aguda."],
[9,"¿Qué otro síntoma es propio de una lesión aguda?",["Moretones e hinchazón extrema","Dolor leve intermitente","Rigidez matutina únicamente","Fatiga muscular general"],0,"Los moretones y la hinchazón extrema son propios de la lesión aguda."],
[9,"¿Qué síntoma grave puede indicar una lesión aguda severa?",["Hueso o articulación fuera de lugar","Enrojecimiento leve de la piel","Sudoración excesiva","Aumento del apetito"],0,"Un hueso o articulación fuera de lugar indica una lesión aguda severa."],
[9,"¿Cuál es un síntoma típico de una lesión crónica?",["Dolor persistente durante el juego","Pérdida total de consciencia","Fiebre alta","Dolor únicamente al despertar"],0,"El dolor persistente durante el juego es típico de la lesión crónica."],
[9,"¿Qué otro síntoma se asocia a una lesión crónica?",["Hinchazón y dolor leve constante en reposo","Deformidad ósea inmediata","Pérdida completa de movilidad","Fractura expuesta"],0,"La hinchazón y el dolor leve constante en reposo se asocian a la lesión crónica."],
[9,"¿Cuál es la causa típica de una lesión crónica en el baloncesto?",["Uso excesivo","Un solo impacto directo","Falta de calentamiento únicamente","Deshidratación severa"],0,"El uso excesivo es la causa típica de una lesión crónica."],
[9,"¿Qué grado de esguince implica la ruptura total del ligamento?",["Grado I","Grado II","Grado III","No se clasifica"],2,"El Grado III implica la ruptura total del ligamento."],
[9,"¿Qué grado de esguince implica solo distensión sin ruptura?",["Grado I","Grado II","Grado III","Ninguno"],0,"El Grado I implica solo distensión sin ruptura."],
[9,"¿Cuál es la clasificación general de lesiones técnicas del baloncesto según el compendio?",["Fracturas, esguinces, desgarros/distensiones y tendinitis","Solo fracturas y esguinces","Solo lesiones musculares","Únicamente lesiones articulares"],0,"La clasificación incluye fracturas, esguinces, desgarros/distensiones y tendinitis."],
[9,"¿Qué diferencia principal existe entre una lesión aguda y una crónica?",["La aguda es repentina e intensa; la crónica es por uso excesivo y persistente","No existe ninguna diferencia","La crónica siempre requiere cirugía inmediata","La aguda nunca presenta dolor"],0,"La aguda es repentina e intensa; la crónica surge por uso excesivo y es persistente."],
[10,"¿Qué mide el seguimiento tecnológico mediante GPS y sensores?",["Datos en tiempo real para optimizar la mecánica de tiro","Solo el peso corporal","El clima durante el partido","La cantidad de espectadores"],0,"El seguimiento tecnológico mide datos en tiempo real para optimizar la mecánica de tiro."],
[10,"¿Qué evalúa principalmente el seguimiento estadístico?",["Indicadores de rendimiento como eficiencia y % de tiro","La nacionalidad de los jugadores","El color del uniforme","La duración del descanso"],0,"El seguimiento estadístico evalúa indicadores de rendimiento como eficiencia y % de tiro."],
[10,"¿Cuántas confederaciones tiene la FIBA?",["3","4","5","6"],2,"La FIBA se organiza en 5 confederaciones."],
[10,"¿Cuáles son las confederaciones de la FIBA?",["África, Américas, Asia, Europa, Oceanía","Norte, Sur, Este, Oeste","América, Europa, Asia","África, Europa, Antártida"],0,"Las confederaciones de la FIBA son África, Américas, Asia, Europa y Oceanía."],
[10,"¿Qué organismo es el rector nacional del baloncesto en México?",["FIBA Américas","ADEMEBA","CONADE","COM"],1,"ADEMEBA es el rector nacional del baloncesto en México."],
[10,"¿A qué instituciones está vinculada ADEMEBA?",["CONADE y COM","FIBA y NBA","ONU y UNESCO","SEP y IMSS"],0,"ADEMEBA está vinculada a CONADE y al COM."],
[10,"¿Desde qué niveles opera ADEMEBA?",["Solo profesional","Desde Micro hasta Sub-21","Solo universitario","Solo Sub-21 en adelante"],1,"ADEMEBA opera desde niveles Micro hasta Sub-21."],
[10,"¿Qué tecnología se usa para el seguimiento en tiempo real del rendimiento de los jugadores?",["GPS y sensores","Rayos X","Ultrasonido","Radar meteorológico"],0,"Se usan GPS y sensores para el seguimiento en tiempo real."],
[10,"¿Qué tipo de datos aporta el seguimiento estadístico al entrenador?",["Eficiencia y porcentaje de tiro","Únicamente la altura de los jugadores","El historial médico completo","La opinión de los árbitros"],0,"Aporta datos de eficiencia y porcentaje de tiro."],
[10,"¿En qué año y país se fundó la FIBA?",["1932 en Suiza","1936 en Alemania","1946 en Estados Unidos","1950 en Argentina"],0,"La FIBA se fundó en 1932 en Suiza."],
[10,"¿Qué representa la sigla FIBA?",["Federación Internacional de Baloncesto","Federación Iberoamericana de Baloncesto","Federación Interna de Básquet Amateur","Fondo Internacional de Baloncesto Amateur"],0,"FIBA representa a la Federación Internacional de Baloncesto."],
[10,"¿Qué representa la sigla ADEMEBA en el contexto mexicano?",["Asociación Deportiva Mexicana de Basquetbol","Academia Deportiva de México para el Basquetbol","Asociación Estatal de Básquet","Administración Deportiva de Basquetbol"],0,"ADEMEBA es la Asociación Deportiva Mexicana de Basquetbol."],
[10,"¿Para qué se utiliza principalmente el seguimiento tecnológico en el baloncesto de alto rendimiento?",["Para optimizar la mecánica de tiro y el rendimiento general","Para reemplazar a los entrenadores","Para sustituir el arbitraje","Para definir el reglamento oficial"],0,"Se utiliza para optimizar la mecánica de tiro y el rendimiento general."],
[10,"¿Qué confederación agrupa a los países del continente americano dentro de la FIBA?",["FIBA Europa","FIBA Américas","FIBA Asia","FIBA Oceanía"],1,"FIBA Américas agrupa a los países del continente americano."],
[10,"¿Cómo se estructura el marco organizacional del baloncesto a nivel internacional y nacional?",["Federación internacional (FIBA) y organismos nacionales como ADEMEBA","Solo por clubes privados","Únicamente por gobiernos locales","No existe una estructura organizacional"],0,"Se estructura mediante la FIBA a nivel internacional y organismos nacionales como ADEMEBA."]
];
const MODULOS = {1:"Génesis y Evolución",2:"Terreno de Juego y Equipo",3:"Arbitraje",4:"Fundamentos Técnicos",5:"Táctica y Estrategia",6:"Planificación del Entrenamiento",7:"Detección de Talento",8:"Capacidades Físicas y Cognitivas",9:"Lesiones Deportivas",10:"Tecnología y Organizaciones"};
const RECO = {
 1:"Repasa la línea histórica: orígenes, hitos clave (1893, 1898, 1932, 1936, 1976) y las 13 reglas de Naismith.",
 2:"Refuerza las medidas oficiales de la cancha, el tablero, el aro y las categorías de balón.",
 3:"Practica identificar las señales arbitrales de tanteo, reloj y faltas.",
 4:"Repasa la Trilogía Técnica (bote, pase, tiro) y los 5 pasos de la ciencia del rebote.",
 5:"Revisa los modelos tácticos ofensivos (Overload, High-Low, Ball Reversal) y la defensa de poste bajo.",
 6:"Repasa las 6 etapas del ciclo de planificación del entrenamiento y su orden correcto.",
 7:"Refuerza las fases sensibles de detección de talento y el concepto de Bio-Banding.",
 8:"Revisa la relación entre percepción visual, decisión cognitiva y ejecución técnica (Dr. Burkhart).",
 9:"Repasa la clasificación de lesiones (fracturas, esguinces Grado I-III, tendinitis) y sus síntomas.",
 10:"Refuerza el marco organizacional (FIBA, confederaciones, ADEMEBA) y el seguimiento tecnológico/estadístico."
};
/* =================== FLASHCARDS (40) [frente, dorso] =================== */
const FC = [
["Regla original #1 de Naismith","El balón puede lanzarse en cualquier dirección con una o ambas manos."],
["Regla original #2 de Naismith","El balón puede golpearse en cualquier dirección, nunca con el puño."],
["Regla original #3 de Naismith","No se puede correr con el balón; se lanza desde donde se captura."],
["Regla original #4 de Naismith","El balón se sujeta solo con las manos."],
["Regla original #5 de Naismith","Prohibido cargar, agarrar, empujar o zancadillear."],
["Regla original #6 de Naismith","Golpear con el puño es falta."],
["Regla original #7 de Naismith","Tres faltas consecutivas otorgan una canasta al equipo rival."],
["Regla original #8 de Naismith","La canasta es válida si el balón entra y permanece en el cesto."],
["Regla original #9 de Naismith","El balón fuera de banda lo devuelve quien lo toque primero."],
["Regla original #10 de Naismith","El \"Umpire\" juzga a los jugadores y anota las faltas."],
["Regla original #11 de Naismith","El \"Referee\" juzga el balón, el tiempo y la posesión."],
["Regla original #12 de Naismith","Dos mitades de 15 minutos con 5 minutos de descanso."],
["Regla original #13 de Naismith","Gana el equipo con más canastas."],
["Dimensiones de la cancha FIBA","28 metros de largo por 15 metros de ancho."],
["Diámetro del círculo central","3.6 metros."],
["Radio del semicírculo de no carga","1.25 metros."],
["Dimensiones del tablero","1.05 x 1.80 m, grosor mínimo de 30 mm."],
["Altura del aro","3.05 metros."],
["Balón categoría #7 (varonil)","74–76 cm de circunferencia, 567–610 g de peso."],
["Balón categoría #6 (femenil)","72–73 cm de circunferencia, 510–567 g de peso."],
["Balón categoría #5 (infantil)","69–70 cm de circunferencia, 470–510 g de peso."],
["Prueba de rebote reglamentario","Al caer desde 1.80 m, el balón debe rebotar entre 1.20 y 1.40 m."],
["Esguince Grado I","Distensión ligamentosa, sin ruptura."],
["Esguince Grado II","Ruptura parcial del ligamento."],
["Esguince Grado III","Ruptura total del ligamento."],
["Síntomas de lesión aguda","Dolor intenso y repentino, hinchazón extrema, incapacidad de mover la articulación."],
["Síntomas de lesión crónica","Dolor persistente en el juego, hinchazón y dolor leve constante en reposo."],
["Técnica (Tríada Deportiva)","Ejecución de movimientos estructurales basados en patrones espaciales modelo. Ej: mecánica de tiro."],
["Táctica (Tríada Deportiva)","Conjuga facultades físicas, técnicas y psicológicas ante el oponente. Ej: tiro con oposición."],
["Estrategia (Tríada Deportiva)","Plan de acción a largo plazo para superar al oponente. Ej: selección de deportistas."],
["Overload (Sobrecarga)","3 jugadores en un mismo sector; zona de impacto: lateral y esquina."],
["High-Low (Poste Alto)","El interior distribuye desde la bombilla; zona de impacto: centro de la zona y tiros libres."],
["Ball Reversal","Circulación rápida sin bote excesivo; impacto en línea de 3 (45°) y perímetro."],
["Fase sensible: Iniciación","6-9 años (Micro e Infantil): 100% lúdico, agilidad, coordinación ojo-mano."],
["Fase sensible: Detección Activa","10-13 años (Pasarela y Cadete): evaluaciones estructuradas y predicción de estatura."],
["Fase sensible: Especialización","14-17 años (Juvenil y Juvenil Mayor): alto rendimiento y adaptación post-estirón puberal."],
["Bio-Banding","Agrupación por maduración física real, no por edad cronológica, evita excluir 'maduradores tardíos'."],
["5 pasos del rebote","1) Brazos elevados 2) Salto vertical 3) Toma en el punto más alto 4) Aseguramiento con ambas manos 5) Protección al bajar."],
["Fundación de la FIBA","1932, en Suiza."],
["ADEMEBA","Rector nacional del baloncesto en México, vinculado a CONADE y COM, desde Micro hasta Sub-21."],
["Confederaciones de la FIBA","África, Américas, Asia, Europa y Oceanía."]
];
/* =================== JUEGO DE EMPAREJAMIENTO (12 pares) =================== */
const MP = [
["Pase de pecho","Pase directo a la altura del pecho del receptor"],
["Pase picado","Bota en el suelo antes de llegar al receptor"],
["Pase elevado","Trayectoria alta por encima de la defensa"],
["Pase al toque","Se entrega de forma directa y rápida a corta distancia"],
["Pase de béisbol","Lanzamiento largo a una mano, similar al béisbol"],
["Pase saltando","Se ejecuta en el aire, antes de aterrizar"],
["Pase por la espalda","El balón pasa por detrás del cuerpo del pasador"],
["Pase ciego","Se entrega sin mirar directamente al receptor"],
["Esguince Grado I","Distensión ligamentosa sin ruptura"],
["Esguince Grado II","Ruptura parcial del ligamento"],
["Esguince Grado III","Ruptura total del ligamento"],
["Tendinitis de Aquiles","Inflamación del tendón por uso excesivo"]
];
/* =================== PIZARRA TÁCTICA =================== */
const FORMATIONS = {
 overload:{title:"Overload (Sobrecarga)",desc:"3 jugadores se concentran en un mismo lateral para generar superioridad numérica frente a la defensa. Zona de impacto: lateral y esquina.",pos:[[230,410],[250,300],[265,190],[60,370],[150,60]]},
 highlow:{title:"High-Low (Ataque Poste Alto)",desc:"El interior distribuye el balón desde la bombilla hacia el poste bajo. Zona de impacto: centro de la zona y tiros libres.",pos:[[150,410],[75,250],[225,250],[150,150],[150,55]]},
 ballreversal:{title:"Ball Reversal (Inversión y Bloqueos)",desc:"Circulación rápida del balón de lado a lado sin bote excesivo. Zona de impacto: línea de 3 puntos (45°) y perímetro.",pos:[[150,415],[45,290],[255,290],[45,140],[255,140]]},
 zona:{title:"Defensa Zonal 2-3",desc:"Dos defensores cubren el perímetro alto (guardias) y tres cubren la zona baja (alero-pívot-alero), protegiendo el área cercana al aro.",pos:[[95,360],[205,360],[50,170],[150,140],[250,170]]}
};
